name: .NET

on:
  push:
    branches: [ "master", "ap/publish-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.*
    - name: Restore dependencies
      run: dotnet restore SocketComm
    - name: Build
      run: dotnet build SocketComm --no-restore
    - name: Test
      run: dotnet test SocketComm --no-build --verbosity normal
    - name: Build Package
      run: dotnet pack SocketComm --configuration Release
    - name: Push Package
      run: cd SocketComm && dotnet nuget push "bin/Release/SocketComm.*.nupkg" --api-key ${{secrets.GITHUB-PACKAGE-KEY}} --skip-duplicate --source "github"